#!/bin/sh
# Xcode Cloud: write gitignored Secrets.local.xcconfig from workflow env secrets.
# Requires Environment Variable: JVPN_SHARED_TOKEN (secret)
set -euo pipefail

ROOT="${CI_PRIMARY_REPOSITORY_PATH:-}"
if [ -z "$ROOT" ]; then
  ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
fi

CONFIG_DIR="$ROOT/app/Configs"
OUT="$CONFIG_DIR/Secrets.local.xcconfig"

if [ -z "${JVPN_SHARED_TOKEN:-}" ]; then
  echo "error: JVPN_SHARED_TOKEN is not set in the Xcode Cloud workflow environment" >&2
  exit 1
fi

HOST="${JVPN_SERVER_HOST:-vpn.blakout.dev}"
PORT="${JVPN_SERVER_PORT:-443}"

mkdir -p "$CONFIG_DIR"
cat > "$OUT" <<EOF
// Generated by ci_scripts/ci_pre_xcodebuild.sh — do not commit
JVPN_SERVER_HOST = ${HOST}
JVPN_SERVER_PORT = ${PORT}
JVPN_SHARED_TOKEN = ${JVPN_SHARED_TOKEN}
EOF

echo "Wrote $OUT (token length=${#JVPN_SHARED_TOKEN})"
