package bootstrap

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/hex"
	"encoding/pem"
	"fmt"
	"log"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Ensure creates dataDir if needed, then creates token, TLS cert, and key PEMs when missing.
// Token is 32 random bytes as hex. Cert is ECDSA P-256, self-signed, TLS 1.3–capable.
// Extra DNS names and IPs from env JVPN_TLS_SAN (comma-separated, e.g. "vpn.example.com,203.0.113.5").
func Ensure(dataDir, certPath, keyPath, tokenPath string) error {
	if dataDir != "" && dataDir != "." {
		if err := os.MkdirAll(dataDir, 0750); err != nil {
			return fmt.Errorf("data dir: %w", err)
		}
	}
	for _, p := range []string{certPath, keyPath, tokenPath} {
		d := filepath.Dir(p)
		if d != "." && d != "" {
			if err := os.MkdirAll(d, 0750); err != nil {
				return fmt.Errorf("mkdir %s: %w", d, err)
			}
		}
	}

	if _, err := os.Stat(tokenPath); os.IsNotExist(err) {
		b := make([]byte, 32)
		if _, err := rand.Read(b); err != nil {
			return err
		}
		if err := os.WriteFile(tokenPath, []byte(hex.EncodeToString(b)), 0600); err != nil {
			return fmt.Errorf("write token: %w", err)
		}
		log.Printf("created token file %s (use this secret in the JVPN client)", tokenPath)
	} else if err != nil {
		return fmt.Errorf("token file: %w", err)
	}

	_, certErr := os.Stat(certPath)
	_, keyErr := os.Stat(keyPath)
	if os.IsNotExist(certErr) || os.IsNotExist(keyErr) {
		if err := writeSelfSigned(certPath, keyPath); err != nil {
			return err
		}
		log.Printf("created self-signed TLS cert %s and key %s (set JVPN_TLS_SAN for extra names/IPs)", certPath, keyPath)
	} else if certErr != nil {
		return certErr
	} else if keyErr != nil {
		return keyErr
	}
	return nil
}

func writeSelfSigned(certPath, keyPath string) error {
	priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return err
	}
	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return err
	}

	dns := []string{"localhost"}
	if h, err := os.Hostname(); err == nil && h != "" {
		dns = append(dns, h)
	}
	ips := []net.IP{net.IPv4(127, 0, 0, 1), net.IPv6loopback}
	if raw := strings.TrimSpace(os.Getenv("JVPN_TLS_SAN")); raw != "" {
		for _, p := range strings.Split(raw, ",") {
			p = strings.TrimSpace(p)
			if p == "" {
				continue
			}
			if ip := net.ParseIP(p); ip != nil {
				ips = appendUniqueIP(ips, ip)
				continue
			}
			dns = appendUnique(dns, p)
		}
	}

	tpl := x509.Certificate{
		SerialNumber: serial,
		Subject:      pkix.Name{Organization: []string{"JVPN (autogenerated)"}},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().Add(825 * 24 * time.Hour),
		KeyUsage:     x509.KeyUsageDigitalSignature,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		DNSNames:     dns,
		IPAddresses:  ips,
	}
	der, err := x509.CreateCertificate(rand.Reader, &tpl, &tpl, priv.Public(), priv)
	if err != nil {
		return err
	}
	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
	keyBytes, err := x509.MarshalECPrivateKey(priv)
	if err != nil {
		return err
	}
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: keyBytes})

	if err := os.WriteFile(certPath, certPEM, 0644); err != nil {
		return err
	}
	return os.WriteFile(keyPath, keyPEM, 0600)
}

func appendUnique(s []string, v string) []string {
	for _, x := range s {
		if x == v {
			return s
		}
	}
	return append(s, v)
}

func appendUniqueIP(s []net.IP, v net.IP) []net.IP {
	for _, x := range s {
		if x.Equal(v) {
			return s
		}
	}
	return append(s, v)
}
